/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "login": [],
    "register": [],
    "provider.google": [],
    "provider.phone": [],
    "provider.phone.verify": [],
    "profile.register": [],
    "profile.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "password.send.link": [],
    "password.reset.link": [],
    "password.edit": [],
    "email.edit": [],
    "verification.verify.email": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send.email": [],
    "logout": [],
    "tokens.index": [
        {
            "name": "name",
            "required": true
        }
    ],
    "tokens.create": [
        {
            "name": "name",
            "required": true
        }
    ],
    "tokens.revoke": [
        {
            "name": "id",
            "required": true
        }
    ],
    "tokens.refresh": [],
    "file.upload": [],
    "file.replace": [],
    "file.delete": [],
    "user.permissions": [
        {
            "name": "user",
            "required": false,
            "binding": "id"
        }
    ],
    "user.sessions": [
        {
            "name": "user",
            "required": false,
            "binding": "id"
        }
    ],
    "user.roles": [
        {
            "name": "user",
            "required": false,
            "binding": "id"
        }
    ],
    "user.by-email": [
        {
            "name": "email",
            "required": true
        }
    ],
    "user.by-phone": [
        {
            "name": "phone",
            "required": true
        }
    ],
    "users.store": [],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.index": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user-sessions.index": [],
    "user-sessions.show": [
        {
            "name": "user_session",
            "required": true
        }
    ],
    "user-sessions.destroy": [
        {
            "name": "user_session",
            "required": true
        }
    ],
    "email.send": [],
    "roles.store": [],
    "roles.show": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.user.index": [
        {
            "name": "user",
            "required": false
        }
    ],
    "permissions.store": [],
    "permissions.show": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "permissions.update": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "permissions.destroy": [
        {
            "name": "permission",
            "required": true,
            "binding": "id"
        }
    ],
    "permissions.user.index": [
        {
            "name": "user",
            "required": false
        }
    ],
    "roles.index": [],
    "permissions.index": [],
    "database.check": [],
    "database.create": [],
    "database.create.post": [],
    "database.migrate": [],
    "database.seed": [],
    "app-settings.index": [],
    "app-settings.update": [],
    "notifications.user.index": [],
    "notifications.user.index-unread": [],
    "notifications.user.index-read": [],
    "notifications.mark": [
        {
            "name": "notification",
            "required": true,
            "binding": "id"
        }
    ],
    "notifications.user.mark-all": [],
    "notifications.destroy": [
        {
            "name": "notification",
            "required": true,
            "binding": "id"
        }
    ],
    "root": [],
    "home.index": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": []
}
}
export {};
